name: Test workflow
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.17", "1.18", "1.19"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup go ${{ matrix.version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}
      - name: Run tests
        run: go test ./...